"""add properties to expenses

Revision ID: e0bf3cfc149c
Revises: f7d0fe90baa6
Create Date: 2026-02-01 12:24:14.112404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e0bf3cfc149c'
down_revision: Union[str, Sequence[str], None] = 'f7d0fe90baa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('expenses', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('expenses', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('expenses', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'category')
    op.drop_column('expenses', 'date')
    op.drop_column('expenses', 'amount')
    op.drop_column('expenses', 'description')
    # ### end Alembic commands ###
